baseURL: "https://www.laboiteabouillons.fr"
theme: lbab-hugo
title: "La boite à bouillons | Concentré d'intelligence collective"
defaultContentLanguage: fr
languageCode: "fr-fr"
hasCJKLanguage: false
enableEmoji: true
googleAnalytics: "" # UA-XXXXXXXX-X
canonifyURLs: false
disablePathToLower: false
enableRobotsTXT: true
pygmentsCodefences: true
pygmentsStyle: "vs"
author: "Anne-Sophie Evrard"
copyright: "Copyright © 2020, Anne-Sophie Evrard, tous droits réservés."
