baseURL: "https://www.laboiteabouillons.fr"
title: "La boite à bouillons | Concentré d'intelligence collective"
theme: lbab-hugo
hasCJKLanguage: false
enableEmoji: true
googleAnalytics: "" # UA-XXXXXXXX-X
canonifyURLs: false
disablePathToLower: false
enableRobotsTXT: true
pygmentsCodefences: true
pygmentsStyle: "vs"
author:
  name: "Anne-Sophie Evrard"
copyright: "Copyright © 2020, Anne-Sophie Evrard, tous droits réservés."
