staticDir:
  - bouillon-creatif/images
  - bouillon-evasion/images
  - bouillon-festif/images
  - bouillon-strategique/images
  - l-esprit/images
  - l-esprit-de-la-boite/images
  - la-fondatrice/images
  - le-reseau/images
  - mentions-legales/images
  - votre-challenge/images
